cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.866138
  brandStrength: 1
  lightness: 0.6319963
  brandColors:
    - '#FFFFFD'
    - '#536068'
    - '#CABFAB'
    - '#1E170D'
    - '#D34225'
  rhythmicContrast: 0.6114739
typography_spectrum: 0.7472015
layout_spectrum: 0.6077694
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Verily
